### ISSUE TITLE
How about an article/announcement on this?

### ISSUE THREAD

**Issue by rfay** [ochorocho/ddev-docker#11]
Is this ready for the world to see and use it? People have been asking about this for *years* and it would be lovely for them to know about it. Anywhere would be great, but how about a guest blog on ddev.com? It's just markdown and super easy, https://github.com/ddev/ddev.com

**Comment by ochorocho** [comment]
I would say yes.

- [x] Documentation for most common setups
- [x] Is used in CI for the [GitLab TYPO3 Template](https://gitlab.com/gitlab-org/project-templates/typo3-distribution/-/jobs/7740773907)
- [x] Weekly updated

I'll write a blog post hopefully this week 🤞

**Comment by rfay** [comment]
Outstanding. People have been looking forward to this as long as I can remember.

**Comment by ochorocho** [comment]
Created a PR for ddev.com, so we can discuss over there: https://github.com/ddev/ddev.com/pull/243
