### ISSUE TITLE
Build failed for "Build and Push Container (v1.23)"

### ISSUE THREAD

**Issue by ochorocho** [ochorocho/ddev-docker#14]
Needs investigation:

https://github.com/ddev/ddev-gitlab-ci/actions/runs/11431540155/job/31808867550

**Comment by ayalon** [comment]
Does this block the 1.23.5 release?

**Comment by ochorocho** [comment]
Yes, the test needs verification. Maybe the text just changed in "All project containers are now ready". But haven't had the time to verify yet. Would be great if could verify and do PR :-) 

```
 # (in test file tests/test.bats, line 67)
#   `[[ "$output" == *"All project containers are now ready."* ]]' failed
```

**Comment by ayalon** [comment]
Here you go:
https://github.com/ddev/ddev-gitlab-ci/pull/15

**Comment by ochorocho** [comment]
Merged, thank you.
