### ISSUE TITLE
Verify the job output 

### ISSUE THREAD

**Issue by ochorocho** [ochorocho/ddev-docker#3]
GitLab Job log:
https://gitlab.com/ochorocho/typo3-distribution/-/jobs/7040611676

Possible errors:

```
app.FindContainerByType(web) failed
app.FindContainerByType(web) failed
```

Playwright seems to complain about the invalid ssl cert:
```
  1) [chromium] › backend.spec.js:4:1 › Backend login ──────────────────────────────────────────────
    Error: page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://typo3-distribution.ddev.site/typo3
```

**Comment by rfay** [comment]
It seems you haven't done a `mkcert -install` here.

**Comment by ochorocho** [comment]
It is already installed. Even tried to run `mkcert -install` in the CI Pipeline but it seems to be already there.
See the Job log:
https://gitlab.com/ochorocho/typo3-distribution/-/jobs/7051081362#L23

```
$ mkcert -install
The local CA is already installed in the system trust store! 👍
```

SSL certificates are in place:
<img width="573" alt="Bildschirmfoto 2024-06-08 um 13 41 21" src="https://github.com/ochorocho/ddev-gitlab-ci/assets/4623070/5f2856ff-40ae-4942-8153-af12ea429613">

**Comment by rfay** [comment]
Oh, I see, I think the chromium container is issuing this error. You'll have to make it trust the certs that you create with mkcer, or else use http.

**Comment by ochorocho** [comment]
> ```
> app.FindContainerByType(web) failed
> app.FindContainerByType(web) failed
> ```

Dunno why this is. But it does not harm in the CI.

The playwright issue is not related to ddev.
