### ISSUE TITLE
Better name for repo? ddev-gitlab-ci maybe?

### ISSUE THREAD

**Issue by rfay** [ochorocho/ddev-docker#6]
The current name here isn't very useful, `ddev-docker`

How about `ddev-gitlab-ci` or `ddev-docker-in-docker`?

**Comment by rfay** [comment]
It sure looks like this is gitlab-ci focused, so I'd be in favor of that being in the title.

**Comment by ochorocho** [comment]
The new project name is "ddev-gitlab-ci".

Thank you :-)

**Comment by rfay** [comment]
Thanks! It will be much easier to point people to.
